// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz25I9tZyfs-IrQ9tvrLEOKHxmuO8FBz0',
    appId: '1:850667870975:web:0581720155b609a14f0aca',
    messagingSenderId: '850667870975',
    projectId: 'tankctl',
    authDomain: 'tankctl.firebaseapp.com',
    storageBucket: 'tankctl.firebasestorage.app',
    measurementId: 'G-YRQMW4ZLN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFRUG67lUZ29qN6OEJXemx2tQPX6M7UUs',
    appId: '1:850667870975:android:b060e1f8c9e851014f0aca',
    messagingSenderId: '850667870975',
    projectId: 'tankctl',
    storageBucket: 'tankctl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSKxpUkNWh8aibDYnCOYI6RWEKCVX3KW0',
    appId: '1:850667870975:ios:c37c19d035d9ddd74f0aca',
    messagingSenderId: '850667870975',
    projectId: 'tankctl',
    storageBucket: 'tankctl.firebasestorage.app',
    iosBundleId: 'com.tankctl.tankctlApp',
  );
}
